### ISSUE TITLE
Aggressive No-Cache Policies Cause Double Request

### ISSUE THREAD

**Issue by johnnyshankman** [tuupola/lazyload#329]
When we create the temporary `<img />` jQuery DOM node in order to trick the browser into loading the resource we shoot ourselves in the foot.

When the load callback is executed and actually swaps the `src` with the `data` attribute, we cause a 2nd request for the same resource (since it refused to cache itself earlier due to its' policy).

**Comment by johnnyshankman** [comment]
Made an ugly PR for dealing with uncacheable resources

https://github.com/tuupola/jquery_lazyload/pull/328

**Comment by tuupola** [comment]
I think this issue does not exist anymore in [2.x](https://github.com/tuupola/jquery_lazyload/tree/2.x).
